### ISSUE TITLE
Missing script: "start"

### ISSUE THREAD

**Issue by edineu** [BinaryLeo/react_feedback_widget_web#1]
Hej Leo, 
I am giving a go and trying to get your application to run after I have followed your instructions.  
On "npm start" I get the following error:

npm ERR! Missing script: "start"
```
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

Would you be ok for you to give help me out to get it up and running, I would appreciate the help?

I thank you in advance.

**Comment by BinaryLeo** [comment]
Hi Edineu. Is your backend running? In this case, you can try running a specific platform (IOS or android) .
or try : npx expo start. Let me know if now you got success.

**Comment by edineu** [comment]
Hey Leo,
Thank you for the reply.
I didn't quite get the 'back-end' running properly -  I am stuck on how to add my own credentials after I have install the dependencies:

Edit your '.env.example' to '.env' and add your credentials
`DATABASE_URL="postgresql://server:password@localhost:5432/databasename?schema=public"`

I did edit the '.env.example' to '.env, but not sure how do i change the credentials on the link provived - I am missing something? And how do I add my own credentails?

I appreciate the help.

NB. I got the web part running fine 🐱‍👤

**Comment by BinaryLeo** [comment]
Hey man! So about the database credentials.  You should create your own database and set up the credentials. When you run the server, Prisma will automatically create the table using the schema. After that when you run the mobile application or the web app. you'll add the initial data through the server and send the data for a mailtrap account
(Need also your own account).

Basically, credentials are made up of password, port and database name
DATABASE_URL="postgresql://server:password@localhost:5432/databasename?schema=public"

the structure is like this
`
-- CreateTable
CREATE TABLE "feedbacks" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "comment" TEXT NOT NULL,
    "screenshot" TEXT,
    CONSTRAINT "feedbacks_pkey" PRIMARY KEY ("id")
);
`


Let me know if you need more details,  Will be a pleasure to understand your needs and guide you!

Note: I'm updating the repo guide, just now! I'll flag the repo as UPDATED at  when I finish
